export const recipeFiles = [
  {
    id: 'example-brioche',
    path: '/data/recipes/example-brioche.md',
  },
  {
    id: 'example-brownie',
    path: '/data/recipes/example-brownie.md',
  },
  { id: 'base-creme-patissiere-standard', path: '/data/recipes/base-creme-patissiere-standard.md' },
  { id: 'base-creme-mousseline-classique', path: '/data/recipes/base-creme-mousseline-classique.md' },
  { id: 'base-pate-a-choux-standard', path: '/data/recipes/base-pate-a-choux-standard.md' },
  { id: 'base-pate-sucree-standard', path: '/data/recipes/base-pate-sucree-standard.md' },
  { id: 'base-ganache-noire-1-1', path: '/data/recipes/base-ganache-noire-1-1.md' },
  { id: 'base-ganache-montee-noire', path: '/data/recipes/base-ganache-montee-noire.md' },
  { id: 'base-biscuit-joconde-standard', path: '/data/recipes/base-biscuit-joconde-standard.md' },
  { id: 'base-dacquoise-amande', path: '/data/recipes/base-dacquoise-amande.md' },
  { id: 'base-meringue-italienne', path: '/data/recipes/base-meringue-italienne.md' },
  { id: 'base-praline-50', path: '/data/recipes/base-praline-50.md' },
  { id: 'base-croustillant-praline', path: '/data/recipes/base-croustillant-praline.md' },
  { id: 'base-cremeux-caramel', path: '/data/recipes/base-cremeux-caramel.md' },
  { id: 'base-caramel-beurre-sale', path: '/data/recipes/base-caramel-beurre-sale.md' },
  { id: 'open-french-meringue-wikibooks', path: '/data/recipes/open-french-meringue-wikibooks.md' },
  { id: 'open-lemon-curd-wikibooks', path: '/data/recipes/open-lemon-curd-wikibooks.md' },
  { id: 'open-basic-whipped-cream-wikibooks', path: '/data/recipes/open-basic-whipped-cream-wikibooks.md' },
  { id: 'open-choux-pastry-economical-cookery', path: '/data/recipes/open-choux-pastry-economical-cookery.md' },
  { id: 'open-ganache-wikibooks-fr', path: '/data/recipes/open-ganache-wikibooks-fr.md' },
  { id: 'open-white-bread-wikibooks', path: '/data/recipes/open-white-bread-wikibooks.md' },
  { id: 'open-plain-bagels-wikibooks', path: '/data/recipes/open-plain-bagels-wikibooks.md' },
  { id: 'open-flaky-pie-crust-wikibooks', path: '/data/recipes/open-flaky-pie-crust-wikibooks.md' },
  { id: 'open-pound-cake-wikibooks', path: '/data/recipes/open-pound-cake-wikibooks.md' },
  { id: 'open-victoria-sandwich-wikibooks', path: '/data/recipes/open-victoria-sandwich-wikibooks.md' },
  { id: 'open-carrot-cake-wikibooks', path: '/data/recipes/open-carrot-cake-wikibooks.md' },
  { id: 'open-creme-brulee-wikibooks', path: '/data/recipes/open-creme-brulee-wikibooks.md' },
  { id: 'open-shortbread-wikibooks', path: '/data/recipes/open-shortbread-wikibooks.md' },
  { id: 'open-basic-scones-wikibooks', path: '/data/recipes/open-basic-scones-wikibooks.md' },
  { id: 'open-chocolate-chip-cookies-wikibooks', path: '/data/recipes/open-chocolate-chip-cookies-wikibooks.md' },
  { id: 'open-banana-nut-muffins-wikibooks', path: '/data/recipes/open-banana-nut-muffins-wikibooks.md' },
  { id: 'open-rich-brownies-wikibooks', path: '/data/recipes/open-rich-brownies-wikibooks.md' },
  { id: 'open-banana-pancakes-wikibooks', path: '/data/recipes/open-banana-pancakes-wikibooks.md' },
  { id: 'open-breakfast-waffles-wikibooks', path: '/data/recipes/open-breakfast-waffles-wikibooks.md' },
  { id: 'open-crepes-wikibooks', path: '/data/recipes/open-crepes-wikibooks.md' },
  { id: 'open-cinnamon-buns-wikibooks', path: '/data/recipes/open-cinnamon-buns-wikibooks.md' },
  { id: 'open-focaccia-wikibooks', path: '/data/recipes/open-focaccia-wikibooks.md' },
  { id: 'open-deep-dish-pizza-wikibooks', path: '/data/recipes/open-deep-dish-pizza-wikibooks.md' },
  { id: 'open-oatmeal-chocolate-chip-cookies-wikibooks', path: '/data/recipes/open-oatmeal-chocolate-chip-cookies-wikibooks.md' },
  { id: 'open-banana-chocolate-chip-muffins-wikibooks', path: '/data/recipes/open-banana-chocolate-chip-muffins-wikibooks.md' },
  { id: 'handwritten-microwave-pudding', path: '/data/recipes/handwritten-microwave-pudding.md' },
  { id: 'handwritten-caramel-syrup', path: '/data/recipes/handwritten-caramel-syrup.md' },
];

export const knowledgeFiles = [
  { id: 'acidity-control', path: '/data/knowledge/acidity-control.md' },
  { id: 'biscuit-joconde-dacquoise', path: '/data/knowledge/biscuit-joconde-dacquoise.md' },
  { id: 'brownie-sugar-control', path: '/data/knowledge/brownie-sugar-control.md' },
  { id: 'baker-agent-test-questions', path: '/data/knowledge/baker-agent-test-questions.md' },
  { id: 'caramel', path: '/data/knowledge/caramel.md' },
  { id: 'creme-mousseline', path: '/data/knowledge/creme-mousseline.md' },
  { id: 'creme-patissiere', path: '/data/knowledge/creme-patissiere.md' },
  { id: 'ganache', path: '/data/knowledge/ganache.md' },
  { id: 'hydrocolloids', path: '/data/knowledge/hydrocolloids.md' },
  { id: 'ingredient-substitution', path: '/data/knowledge/ingredient-substitution.md' },
  { id: 'pan-scaling', path: '/data/knowledge/pan-scaling.md' },
  { id: 'cake-troubleshooting', path: '/data/knowledge/cake-troubleshooting.md' },
  { id: 'cookie-texture-control', path: '/data/knowledge/cookie-texture-control.md' },
  { id: 'muffin-quickbread-method', path: '/data/knowledge/muffin-quickbread-method.md' },
  { id: 'oven-temperature-control', path: '/data/knowledge/oven-temperature-control.md' },
  { id: 'meringue', path: '/data/knowledge/meringue.md' },
  { id: 'mousse-structure', path: '/data/knowledge/mousse-structure.md' },
  { id: 'pate-a-choux', path: '/data/knowledge/pate-a-choux.md' },
  { id: 'pate-sucree', path: '/data/knowledge/pate-sucree.md' },
  { id: 'praline-croustillant', path: '/data/knowledge/praline-croustillant.md' },
];
